### ISSUE TITLE
Publish on Github pages

### ISSUE THREAD

**Issue by mk-pmb** [luxus1337/pong-vanilla-js#2]
Hi! I'd love to try your game. Could you enable Github pages in the repo options and set it to master branch? That way it would hopefully show up on https://luxus1337.github.io/pong-vanilla-js/ .

**Comment by luxus1337** [comment]
It's not a fully playable game, the point is to be a javascript exercise that a developer needs to finish to create a full game. However I still like the fact that you can preview it on github pages. So I enabled it.

Cheers!
